# img feature resolution: [64, 256, 1024, 4096]
# pc feature resolution: [[14, 14], [28, 28], [56, 56], [112, 112]]

ImgAttnRe_cfgs=dict(
    high_score_ratio_list=[0.4, 0.4, 0.4, 0.4],
    low_score_ratio_list=[0.73, 0.73, 0.73, 0.73],
    sa_cfgs_list=[[dict(with_cp=False,
                        window_size_int=6,
                        mlp_ratio=4,
                        norm_cfg=dict(type='LN', requires_grad=True),
                        drop_rate=0.,
                        drop_path_rate=0.,
                        act_cfg=dict(type='GELU'),
                        window_size=[6, 6],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,
                        ), 
                   dict(with_cp=False,
                        window_size_int=3,
                        mlp_ratio=4,
                        norm_cfg=dict(type='LN', requires_grad=True),
                        drop_rate=0.,
                        drop_path_rate=0.,
                        act_cfg=dict(type='GELU'),
                        window_size=[3, 3],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,),], 
                  [dict(with_cp=False,
                        window_size_int=6,
                        mlp_ratio=4,
                        norm_cfg=dict(type='LN', requires_grad=True),
                        drop_rate=0.,
                        drop_path_rate=0.,
                        act_cfg=dict(type='GELU'),
                        window_size=[6, 6],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,), 
                   dict(with_cp=False,
                        window_size_int=3,
                        mlp_ratio=4,
                        norm_cfg=dict(type='LN', requires_grad=True),
                        drop_rate=0.,
                        drop_path_rate=0.,
                        act_cfg=dict(type='GELU'),
                        window_size=[3, 3],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,),], 
                  [dict(with_cp=False,
                        window_size_int=6,
                        mlp_ratio=4,
                        norm_cfg=dict(type='LN', requires_grad=True),
                        drop_rate=0.,
                        drop_path_rate=0.,
                        act_cfg=dict(type='GELU'),
                        window_size=[6, 6],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,), 
                   dict(with_cp=False,
                        window_size_int=3,
                        mlp_ratio=4,
                        norm_cfg=dict(type='LN', requires_grad=True),
                        drop_rate=0.,
                        drop_path_rate=0.,
                        act_cfg=dict(type='GELU'),
                        window_size=[3, 3],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,),]],
    ca_cfgs_list=[dict(mlp_ratio=4,
                       norm_cfg=dict(type='LN', requires_grad=True),
                       drop_rate=0.,
                       drop_path_rate=0.,
                       act_cfg=dict(type='GELU'),
                        window_size=[6, 6],
                        pre_window_size=[3, 3],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,), 
                  dict(mlp_ratio=4,
                       norm_cfg=dict(type='LN', requires_grad=True),
                       drop_rate=0.,
                       drop_path_rate=0.,
                       act_cfg=dict(type='GELU'),
                        window_size=[6, 6],
                        pre_window_size=[3, 3],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,), 
                  dict(mlp_ratio=4,
                       norm_cfg=dict(type='LN', requires_grad=True),
                       drop_rate=0.,
                       drop_path_rate=0.,
                       act_cfg=dict(type='GELU'),
                        window_size=[6, 6],
                        pre_window_size=[3, 3],
                        num_heads=8,
                        qk_scale=None,
                        qkv_bias=True,
                        attn_drop_rate=0.,),],
    num_neighbor_list=[9, 9, 9, 9],
    depth_in_one_layer=1,
    sequence_length=196,
    first_SA_block_cfgs=dict(num_blocks=3,
                             n_head=8),
    attn_type='mean',
    attn_use_type='mean',
    feat_attn_type='only_re_feat',
    only_re_feat_type=1,
    to_aggr_feat_select_type=3,
    feat_fuse_type='mean',
    )

PcAttnRe_cfgs=dict(
    high_score_ratio_list=[0.4, 0.4, 0.4, 0.4],
    low_score_ratio_list=[0.73, 0.73, 0.73, 0.73],
    sa_cfgs_list=[[dict(neighbours=8,
                       drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,),
                    dict(neighbours=4,
                       drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,)],
                  [dict(neighbours=8,
                       drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,),
                    dict(neighbours=4,
                       drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,)],
                  [dict(neighbours=8,
                       drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,),
                    dict(neighbours=4,
                       drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,)],],
    ca_cfgs_list=[dict(drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,), 
                  dict(drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,),
                  dict(drop_path_rate=0.,
                       groups=32,
                       attn_drop_rate=0.,
                       qkv_bias=True,
                       pe_multiplier=False,
                       pe_bias=True,),],
    same_res_num_neighbor_list=[8, 8, 8, 8],
    diff_res_num_neighbor_list=[64, 4, 4, 4],
    depth_in_one_layer=1,
    sequence_length=64,
    use_pos_emb=True,
    first_SA_block_cfgs=dict(num_blocks=3,
                             n_head=8),
    attn_type='mean',
    attn_use_type='mean',
    feat_attn_type='only_re_feat',
    to_aggr_feat_select_type=3,
    feat_fuse_type='mean',
    )

out_dim=256